// <auto-generated />

using ASP.NET_Core_MVC_Basic.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace ASP.NET_Core_MVC_Basic.Migrations
{
    [DbContext(typeof(ApplicationDdContext))]
    internal class ApplicationDdContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("ASP.NET_Core_MVC_Basic.Models.ApplicationType", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .UseIdentityColumn();

                b.Property<string>("Name")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("ApplicationType");
            });

            modelBuilder.Entity("ASP.NET_Core_MVC_Basic.Models.CategoryModel", b =>
            {
                b.Property<int>("CategoryId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .UseIdentityColumn();

                b.Property<string>("CategoryName")
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("DisplayOrder")
                    .HasColumnType("int");

                b.HasKey("CategoryId");

                b.ToTable("Category");
            });
#pragma warning restore 612, 618
        }
    }
}